ERROR - 2022-09-06 04:14:14 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'jobpro_answer'@'localhost' (using password: YES) in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'jobpro_answer', 'data_989answe', 'jobpro_answer', 3306, '', 0)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(35): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->login()
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(35): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->login()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-09-06 04:14:14 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tb_silp_line`
WHERE `name_id` = :name_id:
AND `pass` = :pass:
GROUP BY `name_id`', [...], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Silpline.php(35): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Silpline->login()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-09-06 04:14:25 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'jobpro_answer'@'localhost' (using password: YES) in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'jobpro_answer', 'data_989answe', 'jobpro_answer', 3306, '', 0)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(72): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->getSilp('HTC01-650073')
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(72): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->getSilp('HTC01-650073')
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-09-06 04:14:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tb_silp_line`
WHERE `name_id` = :name_id:
GROUP BY `paynum_month`', [...], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Silpline.php(72): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Silpline->getSilp('HTC01-650073')
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-09-06 20:54:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'jobpro_answer'@'localhost' (using password: YES) in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'jobpro_answer', 'data_989answe', 'jobpro_answer', 3306, '', 0)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(35): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->login()
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(35): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->login()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-09-06 20:54:46 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tb_silp_line`
WHERE `name_id` = :name_id:
AND `pass` = :pass:
GROUP BY `name_id`', [...], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Silpline.php(35): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Silpline->login()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-09-06 20:55:55 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'jobpro_answer'@'localhost' (using password: YES) in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'jobpro_answer', 'data_989answe', 'jobpro_answer', 3306, '', 0)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(18): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->index()
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(18): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->index()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-09-06 20:55:55 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tb_silp_line`
ORDER BY `name_id` DESC', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Silpline.php(18): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Silpline->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
