ERROR - 2022-08-30 21:54:27 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 171, Array)
#1 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('http://119.59.9...', 'jobpro_answer', 'data_989answer', 'jobpro_answer', 3306, '', 0)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(50): CodeIgniter\BaseModel->findAll()
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->getSilp('HTC01-650073')
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#10 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('http://119.59.9...', 'jobpro_answer', 'data_989answer', 'jobpro_answer', 3306, '', 0)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(50): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->getSilp('HTC01-650073')
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(50): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->getSilp('HTC01-650073')
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-08-30 21:54:27 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tb_silp_line`
WHERE `name_id` = :name_id:', [...], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Silpline.php(50): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Silpline->getSilp('HTC01-650073')
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-08-30 21:55:46 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 171, Array)
#1 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('http://119.59.9...', 'jobpro_answer', 'data_989answer', 'jobpro_answer', 3306, '', 0)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\apibot\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\apibot\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(50): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->getSilp('HTC01-650073')
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#10 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('http://119.59.9...', 'jobpro_answer', 'data_989answer', 'jobpro_answer', 3306, '', 0)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\apibot\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apibot\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(50): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->getSilp('HTC01-650073')
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\apibot\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\apibot\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(50): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->getSilp('HTC01-650073')
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-08-30 21:55:46 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tb_silp_line`
WHERE `name_id` = :name_id:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(622): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Silpline.php(50): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Silpline->getSilp('HTC01-650073')
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-30 22:00:02 --> syntax error, unexpected 'if' (T_IF)
in APPPATH\Config\Routes.php on line 60.
 1 SYSTEMPATH\CodeIgniter.php(406): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 2 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-08-30 22:01:01 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 171, Array)
#1 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('http://119.59.9...', 'jobpro_answer', 'data_989answer', 'jobpro_answer', 3306, '', 0)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(18): CodeIgniter\BaseModel->findAll()
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->index()
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#10 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('http://119.59.9...', 'jobpro_answer', 'data_989answer', 'jobpro_answer', 3306, '', 0)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(18): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->index()
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(18): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->index()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-08-30 22:01:01 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tb_silp_line`
ORDER BY `name_id` DESC', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Silpline.php(18): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Silpline->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-08-30 22:01:08 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 171, Array)
#1 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('http://119.59.9...', 'jobpro_answer', 'data_989answer', 'jobpro_answer', 3306, '', 0)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\apibot\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\apibot\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(58): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->getSilp('HTC01-650073')
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#10 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('http://119.59.9...', 'jobpro_answer', 'data_989answer', 'jobpro_answer', 3306, '', 0)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\apibot\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apibot\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(58): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->getSilp('HTC01-650073')
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\apibot\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\apibot\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(58): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->getSilp('HTC01-650073')
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-08-30 22:01:08 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tb_silp_line`
WHERE `name_id` = :name_id:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(622): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Silpline.php(58): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Silpline->getSilp('HTC01-650073')
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-08-30 22:17:33 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 171, Array)
#1 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('http://119.59.9...', 'jobpro_answer', 'data_989answer', 'jobpro_answer', 3306, '', 0)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(30): CodeIgniter\BaseModel->findAll()
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->login()
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#10 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('http://119.59.9...', 'jobpro_answer', 'data_989answer', 'jobpro_answer', 3306, '', 0)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(30): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->login()
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(30): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->login()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-08-30 22:17:33 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tb_silp_line`
WHERE `name_id` = :name_id:
AND `pass` = :pass:', [...], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Silpline.php(30): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Silpline->login()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-08-30 22:17:40 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 171, Array)
#1 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('http://119.59.9...', 'jobpro_answer', 'data_989answer', 'jobpro_answer', 3306, '', 0)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(18): CodeIgniter\BaseModel->findAll()
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->index()
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#10 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('http://119.59.9...', 'jobpro_answer', 'data_989answer', 'jobpro_answer', 3306, '', 0)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(18): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->index()
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#9 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\apibot\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\apibot\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\apibot\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\apibot\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\apibot\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\apibot\app\Controllers\Silpline.php(18): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\apibot\system\CodeIgniter.php(904): App\Controllers\Silpline->index()
#7 C:\xampp\htdocs\apibot\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
#8 C:\xampp\htdocs\apibot\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apibot\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\apibot\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-08-30 22:17:40 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tb_silp_line`
ORDER BY `name_id` DESC', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Silpline.php(18): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Silpline->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Silpline))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
